### PR TITLE
68-Populate dialog data

### PR DESCRIPTION
**Pull request by DonutPirate**
Got all dialog data passing. Date, times, and datetime-locals are formatted (as strings) in the dummy constructors as they would appear when a user used the selectors in the add/search dialogs.

### CODE REVIEW

**Comment by Natoman95** [comment]
This all looks great. A couple questions about the requests though. Is there some way we can separate the date and time stamps? It's pretty difficult to read all on one line like that. The icons for earliest and latest possible dates don't quite make sense to me. And then I think you may have missed the dialogs on the search page. The results still show generic data when you click on them.

**Comment by DonutPirate** [comment]
Yeah, I think I did miss the search results now that you mention it. The date/time is together as of now because it is inputted as a datetime-local. If we had more intuitive icons for earliest/latest possible departure we'd be in business but I looked through everything and there wasn't a great fit.

**Comment by Natoman95** [comment]
Can we separate out the dates and times? Because for a request you really only need the precision of a date rather than a date and a time right? Try looking here for custom icons: [https://materialdesignicons.com](https://materialdesignicons.com). My add-ui-colors branch has an example of a custom icon.

**Comment by DonutPirate** [comment]
Well for a request it would be nice if you could specify, in case you could leave in the evening of one day but don't want to have to rule out the whole day since you aren't available for it. And I looked there, wasn't much to show for time-related icons.

**Comment by Natoman95** [comment]
Okay, sure. But the time definitely shouldn't be visible on the passenger page until you click on the request. It's just too busy. Display it in the dialog. But even then you'll want to reformat it somehow. 9/12/2017T08:30 is unreadable.

Maybe you can't represent it completely in an icon. Maybe you'll have to have some kind of text. Either way, the icons don't make much sense.

**Comment by DonutPirate** [comment]
I know it's unreadable, I'm emulating via a string what will be passed in via a datetime-local, which we will then need to convert to a readable form. Until we're working with more than a string there's no use messing with it.

**Comment by Natoman95** [comment]
Aaaaaaah. That makes more sense. Cool cool. Might still want to figure out something with the icons though. Maybe the same icon for both and a label?

**Comment by Natoman95** [comment]
I like what you did with the icon and the text labels. I think that works. My one question is why not just use the icon we use for time everywhere else on the requests?

**Comment by Natoman95** [comment]
Oh wait, because it represents both date and time. I think I'm down with that.

**Pull request merged**
